# set terminal png transparent nocrop enhanced font arial 8 size 420,320 
# set output 'datastrings.7.png'
set view 70, 210, 1, 1.7
set ticslevel 0
set title "3D version generated by splot\n(sorry, the axis scales are distorted)" 
set zrange [ -15.0000 : 15.0000 ] noreverse nowriteback
splot 'labelplot.pdb' using 7:8:9 with lines notitle,       '' using 7:8:9:4 with labels left offset 1,0 point 	   ps 2 pt 1 tc lt 3 font "Helvetica,10" notitle
